<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Client;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository implements ClientRepositoryInterface
{

    /**
     * ClientRepository constructor.
     * @param EntityManagerInterface|EntityManager $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct($entityManager, new Mapping\ClassMetadata(Client::class));
    }


    /**
     * @param Client $client
     * @return bool
     */
    public function register(Client $client): bool
    {
        try {
            $this->_em->persist($client);
            $this->_em->flush();
        } catch (\Exception $e) {
            return false;
        }

        return true;
    }

    /**
     * @param Client $client
     * @return bool
     */
    public function update(Client $client): bool
    {
        try {
            $this->_em->merge($client);
            $this->_em->flush();
        } catch (\Exception $e) {
            return false;
        }
        return false;
    }

    /**
     * @return Client[]
     */
    public function listAll(): array
    {
        return $this->findAll();
    }

    /**
     * @param int $id
     * @return Client|Object|null
     */
    public function findOne(int $id): ?Client
    {
        return $this->find(['id' => $id]);
    }

    /**
     * @return Client[]
     */
    public function listActive(): array
    {
        return $this->findBy(['active' => true]);
    }
}
