<?php

namespace AppBundle\Repository;

use AppBundle\Entity\OrderDetail;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\NonUniqueResultException;

/**
 * OrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailRepository extends EntityRepository implements OrderDetailRepositoryInterface
{
    /**
     * OrderDetailRepository constructor.
     * @param EntityManagerInterface|EntityManager $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct($entityManager, new Mapping\ClassMetadata(OrderDetail::class));
    }

    /**
     * @param int $id
     * @return int
     * @throws NonUniqueResultException
     */
    public function getQuantity(int $id): int
    {
        $detail = $this->createQueryBuilder('d')
            ->select('d.quantity as quantity')
            ->where('d.id=:id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getOneOrNullResult();

        return $detail['quantity'];
    }

    /**
     * @param int $id
     * @return OrderDetail|Object|null
     */
    public function findOne(int $id): ?OrderDetail
    {
        return $this->findOneBy(['id' => $id]);
    }
}
