<?php

namespace AppBundle\Repository;

/**
 * ReportDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
