<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ReportDetail;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\NonUniqueResultException;

/**
 * ReportDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportDetailRepository extends EntityRepository implements ReportDetailRepositoryInterface
{
    /**
     * ReportDetailRepository constructor.
     * @param EntityManagerInterface|EntityManager $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct($entityManager, new Mapping\ClassMetadata(ReportDetail::class));
    }


    /**
     * @param int $id
     * @return int
     * @throws NonUniqueResultException
     */
    public function getQuantity(int $id): int
    {
        $detail = $this->createQueryBuilder('r')
            ->select('r.quantity as quantity')
            ->where('r.id=:id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getOneOrNullResult();

        return $detail['quantity'];
    }
}
