<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Report;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Exception;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository implements ReportRepositoryInterface
{
    /**
     * ReportRepository constructor.
     * @param EntityManagerInterface|EntityManager $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct($entityManager, new Mapping\ClassMetadata(Report::class));
    }

    /**
     * @param Report $report
     * @return bool
     */
    public function insert(Report $report): bool
    {
        try {
            $this->_em->persist($report);
            $this->_em->flush();
        } catch (Exception $e) {
            return false;
        }
        return true;
    }

    /**
     * @param Report $report
     * @return bool
     */
    public function update(Report $report): bool
    {
        try {
            $this->_em->merge($report);
            $this->_em->flush();
        } catch (Exception $e) {
            return false;
        }
        return true;
    }

    /**
     * @param Report $report
     * @return bool
     */
    public function delete(Report $report): bool
    {
        try {
            $this->_em->remove($report);
            $this->_em->flush();
        } catch (Exception $e) {
            return false;
        }
        return true;
    }

    /**
     * @return Report[]
     */
    public function listAll(): array
    {
        return $this->findAll();
    }

    /**
     * @param int $id
     * @return Report|Object|null
     */
    public function findOne(int $id): ?Report
    {
        return $this->findOneBy(['id' => $id]);
    }
}
