<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ReEntry;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Exception;

/**
 * ReturnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReturnRepository extends EntityRepository implements ReturnRepositoryInterface
{
    /**
     * ReturnRepository constructor.
     * @param EntityManagerInterface|EntityManager $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct($entityManager, new Mapping\ClassMetadata(ReEntry::class));
    }

    /**
     * @param ReEntry $reEntry
     * @return bool
     */
    public function insert(ReEntry $reEntry): bool
    {
        try {
            $this->_em->persist($reEntry);
            $this->_em->flush();
        } catch (Exception $e) {
            return false;
        }
        return true;
    }

    /**
     * @param ReEntry $reEntry
     * @return bool
     */
    public function update(ReEntry $reEntry): bool
    {
        try {
            $this->_em->merge($reEntry);
            $this->_em->flush();
        } catch (Exception $e) {
            return false;
        }
        return true;
    }

    /**
     * @param ReEntry $reEntry
     * @return bool
     */
    public function delete(ReEntry $reEntry): bool
    {
        try {
            $this->_em->remove($reEntry);
            $this->_em->flush();
        } catch (Exception $e) {
            return false;
        }
        return true;
    }

    /**
     * @return ReEntry[]
     */
    public function listAll(): array
    {
        return $this->findAll();
    }

    /**
     * @param int $id
     * @return ReEntry|Object|null
     */
    public function findOne(int $id): ?ReEntry
    {
        return $this->findOneBy(['id' => $id]);
    }
}
